CREATE TYPE public.app_role AS ENUM ('admin');
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, role public.app_role NOT NULL, UNIQUE(user_id, role));
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE FUNCTION public.has_role(_user_id uuid, _role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role) $$;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
CREATE POLICY "Own role read" ON public.user_roles FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE TABLE public.menu_categories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, slug text UNIQUE NOT NULL, description text, sort_order int DEFAULT 0, is_active boolean DEFAULT true, created_at timestamptz DEFAULT now());
GRANT SELECT ON public.menu_categories TO anon; GRANT SELECT, INSERT, UPDATE, DELETE ON public.menu_categories TO authenticated; GRANT ALL ON public.menu_categories TO service_role;
ALTER TABLE public.menu_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Visible categories" ON public.menu_categories FOR SELECT TO anon, authenticated USING (is_active = true);
CREATE POLICY "Admin categories" ON public.menu_categories FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE TABLE public.menu_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), category_id uuid REFERENCES public.menu_categories(id) ON DELETE SET NULL, name text NOT NULL, slug text UNIQUE NOT NULL, description text, price numeric(10,2), image_url text, is_featured boolean DEFAULT false, is_active boolean DEFAULT true, sort_order int DEFAULT 0, created_at timestamptz DEFAULT now());
GRANT SELECT ON public.menu_items TO anon; GRANT SELECT, INSERT, UPDATE, DELETE ON public.menu_items TO authenticated; GRANT ALL ON public.menu_items TO service_role;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Visible items" ON public.menu_items FOR SELECT TO anon, authenticated USING (is_active = true);
CREATE POLICY "Admin items" ON public.menu_items FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE TABLE public.gallery_images (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL, category text NOT NULL DEFAULT 'Food', image_url text NOT NULL, alt_text text NOT NULL, sort_order int DEFAULT 0, is_active boolean DEFAULT true, created_at timestamptz DEFAULT now());
GRANT SELECT ON public.gallery_images TO anon; GRANT SELECT, INSERT, UPDATE, DELETE ON public.gallery_images TO authenticated; GRANT ALL ON public.gallery_images TO service_role;
ALTER TABLE public.gallery_images ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Visible gallery" ON public.gallery_images FOR SELECT TO anon, authenticated USING (is_active = true);
CREATE POLICY "Admin gallery" ON public.gallery_images FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE TABLE public.reviews (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), customer_name text NOT NULL, rating int NOT NULL CHECK (rating BETWEEN 1 AND 5), review_text text NOT NULL, review_date date, source text DEFAULT 'Google', is_featured boolean DEFAULT false, is_active boolean DEFAULT true, created_at timestamptz DEFAULT now());
GRANT SELECT ON public.reviews TO anon; GRANT SELECT, INSERT, UPDATE, DELETE ON public.reviews TO authenticated; GRANT ALL ON public.reviews TO service_role;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Visible reviews" ON public.reviews FOR SELECT TO anon, authenticated USING (is_active = true);
CREATE POLICY "Admin reviews" ON public.reviews FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE TABLE public.contact_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, email text NOT NULL, phone text, message text NOT NULL, status text NOT NULL DEFAULT 'New' CHECK (status IN ('New','Read','Replied','Archived')), created_at timestamptz DEFAULT now());
GRANT INSERT ON public.contact_messages TO anon; GRANT SELECT, INSERT, UPDATE, DELETE ON public.contact_messages TO authenticated; GRANT ALL ON public.contact_messages TO service_role;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public contact submit" ON public.contact_messages FOR INSERT TO anon, authenticated WITH CHECK (length(name) BETWEEN 1 AND 120 AND length(message) BETWEEN 1 AND 4000 AND length(email) BETWEEN 3 AND 255);
CREATE POLICY "Admin contacts" ON public.contact_messages FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE INDEX menu_items_category_idx ON public.menu_items(category_id, sort_order);
CREATE INDEX contact_messages_created_idx ON public.contact_messages(created_at DESC);